const dmlOrderLineData = [
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-15T15:53:04",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_15_DeBlaze_Grill_[RML_Restaurant_Group]",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 8,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Vestigo",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-15T15:53:25",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_15_DeBlaze_Grill_[RML_Restaurant_Group]",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 8,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Celso",
    COST_PER_UNIT: 10.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-15T15:53:50",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_15_DeBlaze_Grill_[RML_Restaurant_Group]",
    ORDER_LINE_NO: "3",
    ORDER_QTY: 4,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Il Padrone",
    COST_PER_UNIT: 17.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-15T16:21:58",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_15_Alta_Via_-_Market_Square",
    ORDER_LINE_NO: "4",
    ORDER_QTY: 24,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Celso",
    COST_PER_UNIT: 10.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-15T16:22:20",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_15_Alta_Via_-_Market_Square",
    ORDER_LINE_NO: "5",
    ORDER_QTY: 36,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "S - Prosecco",
    COST_PER_UNIT: 12.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T09:08:59",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Alta_Via_[Fox_Chapel_Speciality]",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 24,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Vestigo",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T09:09:19",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Alta_Via_[Fox_Chapel_Speciality]",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 6,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Rosso Montalcino",
    COST_PER_UNIT: 22.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T09:09:43",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Alta_Via_[Fox_Chapel_Speciality]",
    ORDER_LINE_NO: "3",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Riesling",
    COST_PER_UNIT: 17.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T11:22:31",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Michael_As_[Mangia_Italiano]",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 24,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Vestigo",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T11:22:45",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Michael_As_[Mangia_Italiano]",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Nero",
    COST_PER_UNIT: 12.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:32:12",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Dancing_Crab_[Dormont]_Thailand_Eatery",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 36,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Capocanale - MWO",
    COST_PER_UNIT: 15.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:32:30",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Dancing_Crab_[Dormont]_Thailand_Eatery",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 24,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Riesling",
    COST_PER_UNIT: 17.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:35:15",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Olivers_Rooftop_(Scotts_Bay_Front)",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "S - Orange",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:35:31",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Olivers_Rooftop_(Scotts_Bay_Front)",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Grigio",
    COST_PER_UNIT: 16.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:36:07",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Olivers_Rooftop_(Scotts_Bay_Front)",
    ORDER_LINE_NO: "3",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Ypsilon",
    COST_PER_UNIT: 16.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:36:35",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Olivers_Rooftop_(Scotts_Bay_Front)",
    ORDER_LINE_NO: "4",
    ORDER_QTY: 4,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Cab Sauv",
    COST_PER_UNIT: 32.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:36:49",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Olivers_Rooftop_(Scotts_Bay_Front)",
    ORDER_LINE_NO: "5",
    ORDER_QTY: 2,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Libero",
    COST_PER_UNIT: 34.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:41:28",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Fet_Fisk",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 36,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Vermentino",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:41:58",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Fet_Fisk",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "S - Saten Brut",
    COST_PER_UNIT: 39.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:46:03",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Casbah_[El_Grande]",
    ORDER_LINE_NO: "1",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "S - Prosecco",
    COST_PER_UNIT: 12.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:46:19",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Casbah_[El_Grande]",
    ORDER_LINE_NO: "2",
    ORDER_QTY: 12,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Barbera",
    COST_PER_UNIT: 14.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:46:36",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Casbah_[El_Grande]",
    ORDER_LINE_NO: "3",
    ORDER_QTY: 6,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Nebbiolo",
    COST_PER_UNIT: 15.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:47:49",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Casbah_[El_Grande]",
    ORDER_LINE_NO: "4",
    ORDER_QTY: 4,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "R - Ypsilon",
    COST_PER_UNIT: 16.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
  {
    ACTIVE_FLG: "Y",
    ALLOCATION_STRATEGY_ID: null,
    COMP_ID: "AWG",
    CONTENT_STATUS: null,
    COUNTRY_OF_ORIGIN: null,
    DATE_CREATED: "2025-12-16T13:48:03",
    DATE_UPDATED: null,
    HOST_ORDER_LINE_NO: null,
    LOT: null,
    LOT_STATUS: null,
    ORDER_CLASS: "SHIP",
    ORDER_ID: "2025_12_16_Casbah_[El_Grande]",
    ORDER_LINE_NO: "5",
    ORDER_QTY: 2,
    PACK_ID: null,
    PACK_QTY: null,
    PACK_SHORT_ALLOWED: "Y",
    PACK_TYPE: null,
    SKU: "W - Libero",
    COST_PER_UNIT: 34.99,
    UPDATE_APP_NAME: null,
    UPDATE_EMP_ID: null,
    UPDATE_REASON_CODE: null,
  },
];

/*
SELECT JSON_ARRAYAGG(
         JSON_OBJECT(
           'year' VALUE year,
           'month' VALUE month,
           'total_order_qty' VALUE total_order_qty,
           'trend_value' VALUE trend_value
         )
         ORDER BY year, month
       ) AS json_output
FROM (
    SELECT
        TO_CHAR(date_created, 'YYYY') AS year,
        TO_CHAR(date_created, 'MM') AS month,
        SUM(order_qty) AS total_order_qty,
        -- compute trend_value in the same query or source system
        <trend_value expression> AS trend_value
    FROM ksw_order_line
    WHERE date_created < DATE '2026-05-01'
    GROUP BY
        TO_CHAR(date_created, 'YYYY'),
        TO_CHAR(date_created, 'MM')
)
*/
const dmlOrderLineMonthlyTotals = [{ "year": "2023", "month": "02", "total_order_qty": 7, "trend_value": -229.1, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "03", "total_order_qty": 10, "trend_value": -173.8, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "04", "total_order_qty": 40, "trend_value": -118.6, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "05", "total_order_qty": 198, "trend_value": -63.3, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "06", "total_order_qty": 100, "trend_value": -8, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "08", "total_order_qty": 15, "trend_value": 47.2, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "10", "total_order_qty": 30, "trend_value": 102.5, "avg_monthly_total": 461.7 }, { "year": "2023", "month": "12", "total_order_qty": 155, "trend_value": 157.7, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "01", "total_order_qty": 30, "trend_value": 213, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "02", "total_order_qty": 332, "trend_value": 268.2, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "05", "total_order_qty": 1226, "trend_value": 323.5, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "07", "total_order_qty": 24, "trend_value": 378.8, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "09", "total_order_qty": 54, "trend_value": 434, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "10", "total_order_qty": 94, "trend_value": 489.3, "avg_monthly_total": 461.7 }, { "year": "2024", "month": "11", "total_order_qty": 110, "trend_value": 544.5, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "01", "total_order_qty": 100, "trend_value": 599.8, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "03", "total_order_qty": 425, "trend_value": 655.1, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "04", "total_order_qty": 2, "trend_value": 710.3, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "08", "total_order_qty": 671, "trend_value": 765.6, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "09", "total_order_qty": 10, "trend_value": 820.8, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "11", "total_order_qty": 100, "trend_value": 876.1, "avg_monthly_total": 461.7 }, { "year": "2025", "month": "12", "total_order_qty": 2505, "trend_value": 931.4, "avg_monthly_total": 461.7 }, { "year": "2026", "month": "01", "total_order_qty": 2930, "trend_value": 986.6, "avg_monthly_total": 461.7 }, { "year": "2026", "month": "02", "total_order_qty": 600, "trend_value": 1041.9, "avg_monthly_total": 461.7 }, { "year": "2026", "month": "03", "total_order_qty": 75, "trend_value": 1097.1, "avg_monthly_total": 461.7 }, { "year": "2026", "month": "04", "total_order_qty": 2160, "trend_value": 1152.4, "avg_monthly_total": 461.7 }]

window.dmlOrderLineData = dmlOrderLineData;
window.dmlOrderLineMonthlyTotals = dmlOrderLineMonthlyTotals;
